brAthena/brAthena

src/map/clif.c, src/map/clif.h, src/map/packets_struct.h, src/map/pc.c, src/map/skill.c, src/map/unit.c
O pacote implementado em hercules está incorreto, pois foi feito uma duplicata de um já existente, existe um pacote correto para os ícones estou adicionando o mesmo no emulador, irei verificar se no aegis esses pacotes se aplicam a outras situações, caso se aplique atualizei para o pacote correto.
=> Correção no pacote de ícones.

brAthena-15.sln, src/common/cbasetypes.h, src/common/sysinfo.c, vcproj-15/char-server.vcxproj, vcproj-15/char-server.vcxproj.filters, vcproj-15/login-server.vcxproj, vcproj-15/login-server.vcxproj.filters, vcproj-15/map-server.vcxproj, vcproj-15/map-server.vcxproj.filters, vcproj-15/mapcache.vcxproj, vcproj-15/mapcache.vcxproj.filters
Como ainda não existe, mais muitos usam visual studio 2015 resolvi adicionar.
=> * Adicionado suporte a Visual Studio 2015.

src/map/packets.h
Adicionado packets pra 2015-11-04aRagexe
Adicionado packets pra 2015-10-29aRagexe
Editado packets pra 2015-05-13aRagexe
Adicionado packets pra 2014-06-12aRagexe - 2014-06-13aRagexe (O mais estavél até o momento)
=> Atualização packets.h pra hexeds 2015

npc/personalizados/eventos/cemiterio_inquieto.txt
Esse evento é legal demais os mortos vivos ficam nascendo em prontera, se souber configurar dá pra colocar mvps.
=> Tradução npc/personalizados/eventos/cemiterio_inquieto.txt

npc/personalizados/campal_aleatoria/flavius.txt
Tradução feita manualmente ao arquivo \campal_aleatoria\flavius.txt
=> Tradução personalizados\flavius.txt

npc/quests/antigeno_mistura.txt
tradução do arquivo original em 16/11/2016
=> tradução antigeno_mistura.txt

npc/personalizados/eventos/cemiterio_inquieto.txt
trocada linhas: 
mes "POr favor, em nome de Odin, ajudem a cidade de Prontera."; 
additem 505,1;
monster "prontera",0,0,0,0,"Zombie",1015,30,"Uneasy_Check::OnZombieDead";
para:
mes "Por favor, em nome de Odin, ajudem a cidade de Prontera.";
getitem 505,1;
areamonster "prontera",0,0,0,0,"Zombie",1015,30,"Uneasy_Check::OnZombieDead";
=> correção do script devido erros de código

npc/eventos/bossnia.txt
Tradução feita com auxilio do babylon
=> tradução npc/eventos/bossnia.txt

src/map/skill.c
Ajustado parametro que estava gerando alerta ao compilar.
=> Correção de commits anteriores

npc/comerciantes/refinador.txt
=> Tradução refinador.txt

npc/comerciantes/encantador_de_slots.txt
=> Tradução encantador_de_slots.txt

npc/comerciantes/encantador_de_slots2.txt
=> Tradução encantador_de_slots2.txt

npc/personalizados/removedor_de_cartas.txt
Nem precisa dizer da nossa velha sábia.
=> Tradução removedor_de_cartas.txt

npc/pre-re/outros/resetador_de_habilidades.txt
Detalhe tem uma similar na pasta RE, mais elas são diferentes.
=> Tradução resetador_de_habilidades.txt - PRE-RE

npc/instancias/torre_sem_fim.txt
Foi traduzido conforme a lógica da coisa.
=> Tradução torre_sem_fim.txt

npc/quests/quests_prontera.txt
Revisar, uma parte do script já foi testada em jogo.
=> Tradução quests_prontera.txt

npc/campais/flavius/flavius_entrada.txt
=> Tradução flavius_entrada.txt

npc/campais/flavius/flavius02.txt
=> Tradução flavius02.txt

npc/campais/flavius/flavius01.txt
=> Tradução flavius01.txt

npc/pre-re/guias/guias_geffen.txt
=> Tradução guias_geffen.txt

npc/campais/bg_principal.txt
=> Tradução bg_principal.txt

npc/comerciantes/aljaves.txt, npc/comerciantes/alugueis_de_criaturas.txt, npc/personalizados/aluguel.txt, npc/re/cidades/dicastes.txt, npc/re/comerciantes/alquimista.txt, npc/re/comerciantes/alugueis_de_criaturas.txt, npc/re/comerciantes/artesao_ninja.txt, npc/re/comerciantes/catalogo.txt, npc/re/comerciantes/comerciantes_3rd.txt, npc/re/comerciantes/diamante.txt, npc/re/comerciantes/encantador_ko.txt, npc/re/comerciantes/flauta_uivante.txt, npc/re/comerciantes/lojas.txt, npc/re/comerciantes/municao.txt, npc/re/comerciantes/refinador.txt
Tradução de Npcs by: Mihael.
//--- Comerciantes
npc/comerciantes/aljaves.txt
npc/comerciantes/alugueis_de_criaturas.txt
//--- Personalizados
npc/personalizados/aluguel.txt
//--- Re Cidades
npc/re/cidades/dicastes.txt
//--- Re Comerciantes
npc/re/comerciantes/alquimista.txt
npc/re/comerciantes/alugueis_de_criaturas.txt
npc/re/comerciantes/artesao_ninja.txt
npc/re/comerciantes/catalogo.txt
npc/re/comerciantes/comerciantes_3rd.txt
npc/re/comerciantes/diamante.txt
npc/re/comerciantes/encantador_ko.txt
npc/re/comerciantes/flauta_uivante.txt
npc/re/comerciantes/lojas.txt
npc/re/comerciantes/municao.txt
npc/re/comerciantes/refinador.txt
=> Traduções de Npcs.

README.md
_Selos de teste
Informação gerais do projeto_
=> Organização da documentação e testes unitários
